# Minecraft & NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21.1.233,)
loader_version_range=[4,)

# Mod Info
mod_id=copycatsign
mod_name=Copycat Sign
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.copycatsign
mod_authors=SirAlusian and Claude
mod_description=Frei platzierbare Bild-Schilder mit waehlbarem Rahmenmaterial - Create-kompatibel (uebersteht das Zusammenbauen von Zuegen, im Gegensatz zu Entity-basierten Gemaelde-Mods).
